services:
  - type: web
    name: recipe-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You'll set this in Render dashboard
      - key: ENVIRONMENT
        value: production
      - key: PROXY_URLS
        sync: false  # Comma-separated proxy URLs like http://user:pass@host:port
      - key: INSTAGRAM_SESSIONID
        sync: false  # Instagram session cookie for authenticated access
      - key: TIKTOK_SESSIONID
        sync: false  # TikTok session cookie for authenticated access
      - key: TIKTOK_WEBID
        sync: false  # TikTok webid cookie (optional, helps with some requests)